version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.7
    commands:
      - yum update -y
      - yum install -y python36u python36u-libs python36u-devel python36u-pip
artifacts:
  files:
    -  README.md
    -  application.py
    -  requirements.txt
eb_codebuild_settings:
  CodeBuildServiceRole: AWSCodePipelineServiceRole-us-east-1-dashpipe
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/standard:2.0
  Timeout: 60
      
